### ISSUE TITLE
Редизайн VK

### ISSUE THREAD

**Issue by UksusoFF** [KonishchevDmitry/vkfeed#9]
Новая версия тут ожидается: https://new.vk.com/blog/redesign
Как дела с ее поддержкой?

**Comment by KonishchevDmitry** [comment]
vkfeed уже давно не парсит HTML (очень неблагодарное занятие), а использует анонимный VK API, который появился спустя некоторое время после появления vkfeed. Поэтому никаких проблем с новой версией быть не должно.

**Comment by UksusoFF** [comment]
Это замечательно. Спасибо!
